# Generated by Django 4.0.3 on 2022-03-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostMdForm',
        ),
    ]
