# Generated by Django 3.2.12 on 2022-03-16 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('note', '0002_delete_postmdform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(db_index=True, max_length=64, unique=True)),
                ('password_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=64, unique=True)),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('content_html', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('important', models.IntegerField(default=0)),
                ('recent_activity', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.user')),
            ],
        ),
    ]
