# Generated by Django 3.2.12 on 2022-03-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_note_profile_user_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
