# Generated by Django 3.2.12 on 2022-03-20 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_note_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Category')),
                ('detail', models.CharField(max_length=100, null=True, verbose_name='Detail')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Tag')),
                ('detail', models.CharField(max_length=100, null=True, verbose_name='Detail')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
            },
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-create_time'], 'verbose_name': 'note manage', 'verbose_name_plural': 'note manage'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='note',
            name='create_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='create time'),
        ),
        migrations.AddField(
            model_name='note',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, verbose_name='note excerpt'),
        ),
        migrations.AddField(
            model_name='note',
            name='views',
            field=models.IntegerField(default=0, verbose_name='the number of views'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(verbose_name='note content'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content_html',
            field=models.TextField(verbose_name='note content html version'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(db_index=True, max_length=64, verbose_name='note title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.user', verbose_name='author'),
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='note.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='note.Tag', verbose_name='Tag'),
        ),
    ]
