# Generated by Django 3.1.7 on 2022-03-26 05:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('target_id', models.IntegerField(default=-1, verbose_name='the id of the target user')),
                ('content', models.TextField(verbose_name='note content')),
                ('content_html', models.TextField(verbose_name='note content html version')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='create time')),
                ('views', models.IntegerField(default=0, verbose_name='the number of views')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.note', verbose_name='comment')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.user', verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='note content')),
                ('content_html', models.TextField(verbose_name='note content html version')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='create time')),
                ('views', models.IntegerField(default=0, verbose_name='the number of views')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.note', verbose_name='note')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.user', verbose_name='author')),
            ],
        ),
    ]
